web:
  build: .
  volumes:
    - ./:/code
  links:
    - db
  ports:
    - 4000:4000
  command: mix phoenix.server
db:
  image: postgres
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_DB: app_dev
  ports:
    - 15432:5432
